/**
 * server/stripe/products.ts
 *
 * Central registry of all Visium Technologies Stripe products and prices.
 * Generated by scripts/setup-stripe-products.mjs — do not edit price IDs manually.
 * To update prices: edit setup-stripe-products.mjs and re-run it, then paste
 * the output here.
 *
 * All prices are in the Stripe SANDBOX (test mode).
 * Switch to live keys in Settings → Payment when ready for production.
 */

export type BillingCycle = 'monthly' | 'annual';

export interface StripeProductEntry {
  /** Stripe product ID */
  productId: string;
  /** Human-readable product name */
  name: string;
  /** Product category for display grouping */
  category: 'Core Platform' | 'Bundle' | 'Vertical Solution';
  /** Monthly base price in USD (for display only) */
  monthlyBaseUsd: number;
  /** Annual discount percentage (0–1) */
  annualDiscount: number;
  /** Stripe price IDs keyed by billing cycle */
  prices: {
    monthly: string;
    annual: string;
  };
  /** Whether this product requires contacting sales (no Stripe price) */
  contactSales?: boolean;
}

export const VISIUM_PRODUCTS: Record<string, StripeProductEntry> = {
  // ── Core Platforms ─────────────────────────────────────────────────────────
  trucontext: {
    productId: 'prod_UKYM2OGkqtDnkJ',
    name: 'TruContext',
    category: 'Core Platform',
    monthlyBaseUsd: 12499,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtG52eZs8bKGLsMAmBZUk4',
      annual:  'price_1TLtG62eZs8bKGLsCSYb7Ffn',
    },
  },
  'truclaw-starter': {
    productId: 'prod_UKYM3n4AkkOseq',
    name: 'TruClaw — Starter',
    category: 'Core Platform',
    monthlyBaseUsd: 1299,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtG92eZs8bKGLsIOXvUBdq',
      annual:  'price_1TLtGB2eZs8bKGLsIOPOIXCF',
    },
  },
  'truclaw-standard': {
    productId: 'prod_UKYMxf88cAHzIQ',
    name: 'TruClaw — Standard',
    category: 'Core Platform',
    monthlyBaseUsd: 9999,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGE2eZs8bKGLsPyFhzI10',
      annual:  'price_1TLtGF2eZs8bKGLs4OA5bN0L',
    },
  },
  'truclaw-enterprise': {
    productId: 'prod_UKYNaCe56OqjP7',
    name: 'TruClaw — Enterprise',
    category: 'Core Platform',
    monthlyBaseUsd: 0,
    annualDiscount: 0.15,
    prices: {
      monthly: 'contact_sales',
      annual:  'contact_sales',
    },
    contactSales: true,
  },
  truinsight: {
    productId: 'prod_UKYN3l0B7eFpai',
    name: 'Tru-InSight',
    category: 'Core Platform',
    monthlyBaseUsd: 7499,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGK2eZs8bKGLslZU5VRjG',
      annual:  'price_1TLtGL2eZs8bKGLs1jdGWwnk',
    },
  },
  eli: {
    productId: 'prod_UKYNZrF6G1PveL',
    name: 'ELI — Emergency Location Intelligence',
    category: 'Core Platform',
    monthlyBaseUsd: 9499,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGO2eZs8bKGLsca4ITCdY',
      annual:  'price_1TLtGP2eZs8bKGLscOjc58Ee',
    },
  },

  // ── Bundle ─────────────────────────────────────────────────────────────────
  'full-suite-bundle': {
    productId: 'prod_UKYNSOjaoWgUfK',
    name: 'Full Suite Bundle',
    category: 'Bundle',
    monthlyBaseUsd: 27500,
    annualDiscount: 0.20,
    prices: {
      monthly: 'price_1TLtGS2eZs8bKGLsaNhLZazi',
      annual:  'price_1TLtGU2eZs8bKGLsl5mmwC4s',
    },
  },

  // ── Vertical Solutions ─────────────────────────────────────────────────────
  'trucontext-oil-gas': {
    productId: 'prod_UKYNvEOcpWxGka',
    name: 'TruContext — Oil & Gas',
    category: 'Vertical Solution',
    monthlyBaseUsd: 24995,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGX2eZs8bKGLsb0OP2Dng',
      annual:  'price_1TLtGZ2eZs8bKGLsuyHQzfme',
    },
  },
  'smart-city-gov': {
    productId: 'prod_UKYNT9lLBSGD62',
    name: 'Smart City — Government',
    category: 'Vertical Solution',
    monthlyBaseUsd: 28000,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGc2eZs8bKGLslCxIyrdS',
      annual:  'price_1TLtGd2eZs8bKGLsBBSdKTyj',
    },
  },
  'smart-city-municipal': {
    productId: 'prod_UKYNsMUivN021w',
    name: 'Smart City — Municipal',
    category: 'Vertical Solution',
    monthlyBaseUsd: 20000,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGg2eZs8bKGLsifIxS8Xk',
      annual:  'price_1TLtGi2eZs8bKGLsiWxcJYCn',
    },
  },
  'campus-security': {
    productId: 'prod_UKYN5SrzwlOK8X',
    name: 'ELI — Campus Security Suite',
    category: 'Vertical Solution',
    monthlyBaseUsd: 9995,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGk2eZs8bKGLsGFX36K7G',
      annual:  'price_1TLtGm2eZs8bKGLsZmN1p0ok',
    },
  },
  'caseforge-legal': {
    productId: 'prod_UKYNNoT1DlMBcC',
    name: 'CaseForge Legal Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 2499,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGp2eZs8bKGLsJodkqEDi',
      annual:  'price_1TLtGq2eZs8bKGLslVoGYNqy',
    },
  },
  'aspire-reporting': {
    productId: 'prod_UKYN7iacimS6qC',
    name: 'ASPIRE Reporting Platform',
    category: 'Vertical Solution',
    monthlyBaseUsd: 1499,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtGt2eZs8bKGLsp3ViKSSk',
      annual:  'price_1TLtGv2eZs8bKGLsb5vAUKxF',
    },
  },
  truaddress: {
    productId: 'prod_UKYNMnU4sQVttr',
    name: 'TruAddress — National Address Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 19950,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtH02eZs8bKGLs7SK287yo',
      annual:  'price_1TLtH22eZs8bKGLshRp8vyud',
    },
  },
  panelpulse: {
    productId: 'prod_UKYN1Rexx1Jsk8',
    name: 'PanelPulse — Utility Grid Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 995,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtH62eZs8bKGLsZrb043Pm',
      annual:  'price_1TLtH72eZs8bKGLskj0atmcH',
    },
  },
  'smart-city-demo': {
    productId: 'prod_UKYNJwZPrrVSJm',
    name: 'Smart City Demo Suite',
    category: 'Vertical Solution',
    monthlyBaseUsd: 4750,
    annualDiscount: 0.15,
    prices: {
      monthly: 'price_1TLtHA2eZs8bKGLsIpiSXAwJ',
      annual:  'price_1TLtHB2eZs8bKGLsiDtOgVjQ',
    },
  },
};

/**
 * Get the Stripe price ID for a given product and billing cycle.
 * Returns null if the product requires contacting sales.
 */
export function getStripePrice(
  productId: string,
  billingCycle: BillingCycle
): string | null {
  const product = VISIUM_PRODUCTS[productId];
  if (!product) return null;
  if (product.contactSales) return null;
  const priceId = product.prices[billingCycle];
  return priceId === 'contact_sales' ? null : priceId;
}

/**
 * Get a human-readable list of all products for a given category.
 */
export function getProductsByCategory(category: StripeProductEntry['category']) {
  return Object.entries(VISIUM_PRODUCTS)
    .filter(([, p]) => p.category === category)
    .map(([id, p]) => ({ id, ...p }));
}
