/**
 * server/stripe/products.ts
 *
 * Central registry of all Visium Technologies Stripe products and prices.
 * Generated by scripts/setup-stripe-products.mjs — do not edit price IDs manually.
 * To update prices: edit setup-stripe-products.mjs and re-run it, then paste
 * the output here.
 *
 * Pricing sourced from Visium_Pricing_Formulas-02.xlsx (Apr 2026).
 * All annual discounts are uniform 10%.
 * All prices are in the Stripe SANDBOX (test mode).
 * Switch to live keys in Settings → Payment when ready for production.
 */

export type BillingCycle = 'monthly' | 'annual';

export interface StripeProductEntry {
  /** Stripe product ID */
  productId: string;
  /** Human-readable product name */
  name: string;
  /** Product category for display grouping */
  category: 'Core Platform' | 'Bundle' | 'Vertical Solution';
  /** Monthly base price in USD (for display only) */
  monthlyBaseUsd: number;
  /** Annual discount percentage (0–1) */
  annualDiscount: number;
  /** Stripe price IDs keyed by billing cycle */
  prices: {
    monthly: string;
    annual: string;
  };
  /** Whether this product requires contacting sales (no Stripe price) */
  contactSales?: boolean;
}

export const VISIUM_PRODUCTS: Record<string, StripeProductEntry> = {
  // ── Core Platforms ─────────────────────────────────────────────────────────
  trucontext: {
    productId: 'prod_UKYM2OGkqtDnkJ',
    name: 'TruContext',
    category: 'Core Platform',
    monthlyBaseUsd: 7995,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXD2eZs8bKGLsQW7smUw3',
      annual:  'price_1TLuXD2eZs8bKGLs0RBYhAJz',
    },
  },
  'truclaw-starter': {
    productId: 'prod_UKYM3n4AkkOseq',
    name: 'TruClaw — Starter',
    category: 'Core Platform',
    monthlyBaseUsd: 1299,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXF2eZs8bKGLsnb4SdDxy',
      annual:  'price_1TLuXF2eZs8bKGLshWr6iGJt',
    },
  },
  'truclaw-standard': {
    productId: 'prod_UKYMxf88cAHzIQ',
    name: 'TruClaw — Standard',
    category: 'Core Platform',
    monthlyBaseUsd: 6995,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXH2eZs8bKGLsgsBS0SzT',
      annual:  'price_1TLuXH2eZs8bKGLsLsMUtAHU',
    },
  },
  'truclaw-enterprise': {
    productId: 'prod_UKYNaCe56OqjP7',
    name: 'TruClaw — Enterprise',
    category: 'Core Platform',
    monthlyBaseUsd: 0,
    annualDiscount: 0.10,
    prices: {
      monthly: 'contact_sales',
      annual:  'contact_sales',
    },
    contactSales: true,
  },
  truinsight: {
    productId: 'prod_UKYN3l0B7eFpai',
    name: 'Tru-InSight',
    category: 'Core Platform',
    monthlyBaseUsd: 7499,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXJ2eZs8bKGLsvh8x7ZvZ',
      annual:  'price_1TLuXK2eZs8bKGLs3RhSw4e5',
    },
  },
  eli: {
    productId: 'prod_UKYNZrF6G1PveL',
    name: 'ELI — Emergency Location Intelligence',
    category: 'Core Platform',
    monthlyBaseUsd: 9499,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXL2eZs8bKGLswAVMblGH',
      annual:  'price_1TLuXL2eZs8bKGLsOBa9I3eJ',
    },
  },

  // ── Bundle ─────────────────────────────────────────────────────────────────
  'full-suite-bundle': {
    productId: 'prod_UKYNSOjaoWgUfK',
    name: 'Full Suite Bundle',
    category: 'Bundle',
    monthlyBaseUsd: 14995,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXN2eZs8bKGLsyMHPgjcH',
      annual:  'price_1TLuXN2eZs8bKGLsEGh6WuCv',
    },
  },

  // ── Vertical Solutions ─────────────────────────────────────────────────────
  'trucontext-oil-gas': {
    productId: 'prod_UKYNvEOcpWxGka',
    name: 'TruContext — Oil & Gas',
    category: 'Vertical Solution',
    monthlyBaseUsd: 8000,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXP2eZs8bKGLsJiqTwSa4',
      annual:  'price_1TLuXP2eZs8bKGLsVkJik5xo',
    },
  },
  'smart-city-gov': {
    productId: 'prod_UKYNT9lLBSGD62',
    name: 'Smart City — Government',
    category: 'Vertical Solution',
    monthlyBaseUsd: 16000,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXR2eZs8bKGLspGtHvLsb',
      annual:  'price_1TLuXR2eZs8bKGLsOIMj4kZb',
    },
  },
  'smart-city-municipal': {
    productId: 'prod_UKYNsMUivN021w',
    name: 'Smart City — Municipal',
    category: 'Vertical Solution',
    monthlyBaseUsd: 12495,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXT2eZs8bKGLscJBVaoRZ',
      annual:  'price_1TLuXT2eZs8bKGLspH6t445J',
    },
  },
  'campus-security': {
    productId: 'prod_UKYN5SrzwlOK8X',
    name: 'ELI — Campus Security Suite',
    category: 'Vertical Solution',
    monthlyBaseUsd: 7995,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXV2eZs8bKGLsWeQ3a980',
      annual:  'price_1TLuXV2eZs8bKGLsBszbAKvx',
    },
  },
  'caseforge-legal': {
    productId: 'prod_UKYNNoT1DlMBcC',
    name: 'CaseForge Legal Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 3499,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXX2eZs8bKGLsrZiRaQVC',
      annual:  'price_1TLuXX2eZs8bKGLsG70QlRoN',
    },
  },
  'aspire-reporting': {
    productId: 'prod_UKYN7iacimS6qC',
    name: 'ASPIRE Reporting Platform',
    category: 'Vertical Solution',
    monthlyBaseUsd: 3499,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXZ2eZs8bKGLs0GbaDSOm',
      annual:  'price_1TLuXZ2eZs8bKGLsG5GDszhj',
    },
  },
  truaddress: {
    productId: 'prod_UKYNMnU4sQVttr',
    name: 'TruAddress — National Address Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 19950,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXb2eZs8bKGLsZUqa5y0o',
      annual:  'price_1TLuXb2eZs8bKGLspUSzu50e',
    },
  },
  panelpulse: {
    productId: 'prod_UKYN1Rexx1Jsk8',
    name: 'PanelPulse — Utility Grid Intelligence',
    category: 'Vertical Solution',
    monthlyBaseUsd: 3995,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXd2eZs8bKGLsJLqxbOqf',
      annual:  'price_1TLuXd2eZs8bKGLsktSQuq6q',
    },
  },
  'smart-city-demo': {
    productId: 'prod_UKYNJwZPrrVSJm',
    name: 'Smart City Demo Suite',
    category: 'Vertical Solution',
    monthlyBaseUsd: 4750,
    annualDiscount: 0.10,
    prices: {
      monthly: 'price_1TLuXe2eZs8bKGLsW9miMMP6',
      annual:  'price_1TLuXf2eZs8bKGLssF9SxMCd',
    },
  },
};

/**
 * Get the Stripe price ID for a given product and billing cycle.
 * Returns null if the product requires contacting sales.
 */
export function getStripePrice(
  productId: string,
  billingCycle: BillingCycle
): string | null {
  const product = VISIUM_PRODUCTS[productId];
  if (!product) return null;
  if (product.contactSales) return null;
  const priceId = product.prices[billingCycle];
  return priceId === 'contact_sales' ? null : priceId;
}

/**
 * Get a human-readable list of all products for a given category.
 */
export function getProductsByCategory(category: StripeProductEntry['category']) {
  return Object.entries(VISIUM_PRODUCTS)
    .filter(([, p]) => p.category === category)
    .map(([id, p]) => ({ id, ...p }));
}
